/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PrismaModelsUser} from './PrismaModelsUser';

/**
 * The AppModelsResponseUser model module.
 * @module model/AppModelsResponseUser
 * @version 0.0.5
 */
export class AppModelsResponseUser {
  /**
   * Constructs a new <code>AppModelsResponseUser</code>.
   * @alias module:model/AppModelsResponseUser
   * @class
   * @param success {Boolean} 
   */
  constructor(success) {
    this.success = success;
  }

  /**
   * Constructs a <code>AppModelsResponseUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppModelsResponseUser} obj Optional instance to populate.
   * @return {module:model/AppModelsResponseUser} The populated <code>AppModelsResponseUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppModelsResponseUser();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('data'))
        obj.data = PrismaModelsUser.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
AppModelsResponseUser.prototype.success = undefined;

/**
 * @member {module:model/PrismaModelsUser} data
 */
AppModelsResponseUser.prototype.data = undefined;

