/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AppModelsRequestUser model module.
 * @module model/AppModelsRequestUser
 * @version 0.0.5
 */
export class AppModelsRequestUser {
  /**
   * Constructs a new <code>AppModelsRequestUser</code>.
   * @alias module:model/AppModelsRequestUser
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AppModelsRequestUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppModelsRequestUser} obj Optional instance to populate.
   * @return {module:model/AppModelsRequestUser} The populated <code>AppModelsRequestUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppModelsRequestUser();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('age'))
        obj.age = ApiClient.convertToType(data['age'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('avatar'))
        obj.avatar = ApiClient.convertToType(data['avatar'], 'String');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
AppModelsRequestUser.prototype.name = undefined;

/**
 * @member {String} language
 */
AppModelsRequestUser.prototype.language = undefined;

/**
 * @member {String} age
 */
AppModelsRequestUser.prototype.age = undefined;

/**
 * @member {String} type
 */
AppModelsRequestUser.prototype.type = undefined;

/**
 * @member {String} avatar
 */
AppModelsRequestUser.prototype.avatar = undefined;

/**
 * @member {Object} metadata
 */
AppModelsRequestUser.prototype.metadata = undefined;

