/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AppModelsRequestSkillTool model module.
 * @module model/AppModelsRequestSkillTool
 * @version 0.0.5
 */
export class AppModelsRequestSkillTool {
  /**
   * Constructs a new <code>AppModelsRequestSkillTool</code>.
   * @alias module:model/AppModelsRequestSkillTool
   * @class
   * @param toolId {String} 
   */
  constructor(toolId) {
    this.toolId = toolId;
  }

  /**
   * Constructs a <code>AppModelsRequestSkillTool</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppModelsRequestSkillTool} obj Optional instance to populate.
   * @return {module:model/AppModelsRequestSkillTool} The populated <code>AppModelsRequestSkillTool</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppModelsRequestSkillTool();
      if (data.hasOwnProperty('toolId'))
        obj.toolId = ApiClient.convertToType(data['toolId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} toolId
 */
AppModelsRequestSkillTool.prototype.toolId = undefined;

