/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AppModelsRequestAiden model module.
 * @module model/AppModelsRequestAiden
 * @version 0.0.5
 */
export class AppModelsRequestAiden {
  /**
   * Constructs a new <code>AppModelsRequestAiden</code>.
   * @alias module:model/AppModelsRequestAiden
   * @class
   * @param name {String} 
   * @param description {String} 
   */
  constructor(name, description) {
    this.name = name;
    this.description = description;
  }

  /**
   * Constructs a <code>AppModelsRequestAiden</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppModelsRequestAiden} obj Optional instance to populate.
   * @return {module:model/AppModelsRequestAiden} The populated <code>AppModelsRequestAiden</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppModelsRequestAiden();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('initialMessage'))
        obj.initialMessage = ApiClient.convertToType(data['initialMessage'], 'String');
      if (data.hasOwnProperty('avatar'))
        obj.avatar = ApiClient.convertToType(data['avatar'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
AppModelsRequestAiden.prototype.name = undefined;

/**
 * @member {String} description
 */
AppModelsRequestAiden.prototype.description = undefined;

/**
 * @member {String} initialMessage
 */
AppModelsRequestAiden.prototype.initialMessage = undefined;

/**
 * @member {String} avatar
 */
AppModelsRequestAiden.prototype.avatar = undefined;

