/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AppModelsRequestSkillInvoke model module.
 * @module model/AppModelsRequestSkillInvoke
 * @version 0.0.5
 */
export class AppModelsRequestSkillInvoke {
  /**
   * Constructs a new <code>AppModelsRequestSkillInvoke</code>.
   * @alias module:model/AppModelsRequestSkillInvoke
   * @class
   * @param input {String} 
   * @param enableStreaming {Boolean} 
   */
  constructor(input, enableStreaming) {
    this.input = input;
    this.enableStreaming = enableStreaming;
  }

  /**
   * Constructs a <code>AppModelsRequestSkillInvoke</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppModelsRequestSkillInvoke} obj Optional instance to populate.
   * @return {module:model/AppModelsRequestSkillInvoke} The populated <code>AppModelsRequestSkillInvoke</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppModelsRequestSkillInvoke();
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], 'String');
      if (data.hasOwnProperty('sessionId'))
        obj.sessionId = ApiClient.convertToType(data['sessionId'], 'String');
      if (data.hasOwnProperty('enableStreaming'))
        obj.enableStreaming = ApiClient.convertToType(data['enableStreaming'], 'Boolean');
      if (data.hasOwnProperty('outputSchema'))
        obj.outputSchema = ApiClient.convertToType(data['outputSchema'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} input
 */
AppModelsRequestSkillInvoke.prototype.input = undefined;

/**
 * @member {String} sessionId
 */
AppModelsRequestSkillInvoke.prototype.sessionId = undefined;

/**
 * @member {Boolean} enableStreaming
 */
AppModelsRequestSkillInvoke.prototype.enableStreaming = undefined;

/**
 * @member {String} outputSchema
 */
AppModelsRequestSkillInvoke.prototype.outputSchema = undefined;

