/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AppModelsRequestAidenStep model module.
 * @module model/AppModelsRequestAidenStep
 * @version 0.0.5
 */
export class AppModelsRequestAidenStep {
  /**
   * Constructs a new <code>AppModelsRequestAidenStep</code>.
   * @alias module:model/AppModelsRequestAidenStep
   * @class
   * @param order {Number} 
   * @param skillId {String} 
   * @param input {String} 
   * @param output {String} 
   */
  constructor(order, skillId, input, output) {
    this.order = order;
    this.skillId = skillId;
    this.input = input;
    this.output = output;
  }

  /**
   * Constructs a <code>AppModelsRequestAidenStep</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppModelsRequestAidenStep} obj Optional instance to populate.
   * @return {module:model/AppModelsRequestAidenStep} The populated <code>AppModelsRequestAidenStep</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppModelsRequestAidenStep();
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], 'Number');
      if (data.hasOwnProperty('skillId'))
        obj.skillId = ApiClient.convertToType(data['skillId'], 'String');
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], 'String');
      if (data.hasOwnProperty('output'))
        obj.output = ApiClient.convertToType(data['output'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} order
 */
AppModelsRequestAidenStep.prototype.order = undefined;

/**
 * @member {String} skillId
 */
AppModelsRequestAidenStep.prototype.skillId = undefined;

/**
 * @member {String} input
 */
AppModelsRequestAidenStep.prototype.input = undefined;

/**
 * @member {String} output
 */
AppModelsRequestAidenStep.prototype.output = undefined;

