/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PrismaModelsTool} from './PrismaModelsTool';

/**
 * The AppModelsResponseTool model module.
 * @module model/AppModelsResponseTool
 * @version 0.0.5
 */
export class AppModelsResponseTool {
  /**
   * Constructs a new <code>AppModelsResponseTool</code>.
   * @alias module:model/AppModelsResponseTool
   * @class
   * @param success {Boolean} 
   */
  constructor(success) {
    this.success = success;
  }

  /**
   * Constructs a <code>AppModelsResponseTool</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppModelsResponseTool} obj Optional instance to populate.
   * @return {module:model/AppModelsResponseTool} The populated <code>AppModelsResponseTool</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppModelsResponseTool();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('data'))
        obj.data = PrismaModelsTool.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
AppModelsResponseTool.prototype.success = undefined;

/**
 * @member {module:model/PrismaModelsTool} data
 */
AppModelsResponseTool.prototype.data = undefined;

