/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AppModelsRequestSkillDatasource model module.
 * @module model/AppModelsRequestSkillDatasource
 * @version 0.0.5
 */
export class AppModelsRequestSkillDatasource {
  /**
   * Constructs a new <code>AppModelsRequestSkillDatasource</code>.
   * @alias module:model/AppModelsRequestSkillDatasource
   * @class
   * @param datasourceId {String} 
   */
  constructor(datasourceId) {
    this.datasourceId = datasourceId;
  }

  /**
   * Constructs a <code>AppModelsRequestSkillDatasource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppModelsRequestSkillDatasource} obj Optional instance to populate.
   * @return {module:model/AppModelsRequestSkillDatasource} The populated <code>AppModelsRequestSkillDatasource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppModelsRequestSkillDatasource();
      if (data.hasOwnProperty('datasourceId'))
        obj.datasourceId = ApiClient.convertToType(data['datasourceId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} datasourceId
 */
AppModelsRequestSkillDatasource.prototype.datasourceId = undefined;

