/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ConversationCreation model module.
 * @module model/ConversationCreation
 * @version 0.0.5
 */
export class ConversationCreation {
  /**
   * Constructs a new <code>ConversationCreation</code>.
   * @alias module:model/ConversationCreation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ConversationCreation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConversationCreation} obj Optional instance to populate.
   * @return {module:model/ConversationCreation} The populated <code>ConversationCreation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ConversationCreation();
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} metadata
 */
ConversationCreation.prototype.metadata = undefined;

