/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Memory} from './Memory';
import {PrismaModelsUser} from './PrismaModelsUser';

/**
 * The Conversation model module.
 * @module model/Conversation
 * @version 0.0.5
 */
export class Conversation {
  /**
   * Constructs a new <code>Conversation</code>.
   * Represents a Conversation record
   * @alias module:model/Conversation
   * @class
   * @param id {String} 
   * @param userId {String} 
   * @param locationId {String} 
   * @param isActive {Boolean} 
   * @param createdAt {Date} 
   */
  constructor(id, userId, locationId, isActive, createdAt) {
    this.id = id;
    this.userId = userId;
    this.locationId = locationId;
    this.isActive = isActive;
    this.createdAt = createdAt;
  }

  /**
   * Constructs a <code>Conversation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Conversation} obj Optional instance to populate.
   * @return {module:model/Conversation} The populated <code>Conversation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Conversation();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = PrismaModelsUser.constructFromObject(data['user']);
      if (data.hasOwnProperty('locationId'))
        obj.locationId = ApiClient.convertToType(data['locationId'], 'String');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], 'String');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('messages'))
        obj.messages = ApiClient.convertToType(data['messages'], [Memory]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Conversation.prototype.id = undefined;

/**
 * @member {String} userId
 */
Conversation.prototype.userId = undefined;

/**
 * @member {module:model/PrismaModelsUser} user
 */
Conversation.prototype.user = undefined;

/**
 * @member {String} locationId
 */
Conversation.prototype.locationId = undefined;

/**
 * @member {String} metadata
 */
Conversation.prototype.metadata = undefined;

/**
 * @member {Boolean} isActive
 */
Conversation.prototype.isActive = undefined;

/**
 * @member {Date} createdAt
 */
Conversation.prototype.createdAt = undefined;

/**
 * @member {Array.<module:model/Memory>} messages
 */
Conversation.prototype.messages = undefined;

