/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class DatasourceStatus.
 * @enum {String}
 * @readonly
 */
const DatasourceStatus = {
  /**
   * value: "IN_PROGRESS"
   * @const
   */
  IN_PROGRESS: "IN_PROGRESS",

  /**
   * value: "DONE"
   * @const
   */
  DONE: "DONE",

  /**
   * value: "FAILED"
   * @const
   */
  FAILED: "FAILED",

  /**
   * Returns a <code>DatasourceStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DatasourceStatus} The enum <code>DatasourceStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DatasourceStatus};