/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class DatasourceType.
 * @enum {String}
 * @readonly
 */
const DatasourceType = {
  /**
   * value: "TXT"
   * @const
   */
  TXT: "TXT",

  /**
   * value: "PDF"
   * @const
   */
  PDF: "PDF",

  /**
   * value: "CSV"
   * @const
   */
  CSV: "CSV",

  /**
   * value: "PPTX"
   * @const
   */
  PPTX: "PPTX",

  /**
   * value: "XLSX"
   * @const
   */
  XLSX: "XLSX",

  /**
   * value: "DOCX"
   * @const
   */
  DOCX: "DOCX",

  /**
   * value: "GOOGLE_DOC"
   * @const
   */
  GOOGLE_DOC: "GOOGLE_DOC",

  /**
   * value: "YOUTUBE"
   * @const
   */
  YOUTUBE: "YOUTUBE",

  /**
   * value: "GITHUB_REPOSITORY"
   * @const
   */
  GITHUB_REPOSITORY: "GITHUB_REPOSITORY",

  /**
   * value: "MARKDOWN"
   * @const
   */
  MARKDOWN: "MARKDOWN",

  /**
   * value: "WEBPAGE"
   * @const
   */
  WEBPAGE: "WEBPAGE",

  /**
   * value: "AIRTABLE"
   * @const
   */
  AIRTABLE: "AIRTABLE",

  /**
   * value: "STRIPE"
   * @const
   */
  STRIPE: "STRIPE",

  /**
   * value: "NOTION"
   * @const
   */
  NOTION: "NOTION",

  /**
   * value: "SITEMAP"
   * @const
   */
  SITEMAP: "SITEMAP",

  /**
   * value: "URL"
   * @const
   */
  URL: "URL",

  /**
   * value: "FUNCTION"
   * @const
   */
  FUNCTION: "FUNCTION",

  /**
   * Returns a <code>DatasourceType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DatasourceType} The enum <code>DatasourceType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DatasourceType};