/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class Language.
 * @enum {String}
 * @readonly
 */
const Language = {
  /**
   * value: "GERMAN"
   * @const
   */
  GERMAN: "GERMAN",

  /**
   * value: "FRANCE"
   * @const
   */
  FRANCE: "FRANCE",

  /**
   * value: "ENGLISH"
   * @const
   */
  ENGLISH: "ENGLISH",

  /**
   * value: "SPAIN"
   * @const
   */
  SPAIN: "SPAIN",

  /**
   * Returns a <code>Language</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/Language} The enum <code>Language</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Language};