/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Conversation} from './Conversation';
import {PrismaModelsUser} from './PrismaModelsUser';

/**
 * The Memory model module.
 * @module model/Memory
 * @version 0.0.5
 */
export class Memory {
  /**
   * Constructs a new <code>Memory</code>.
   * Represents a Memory record
   * @alias module:model/Memory
   * @class
   * @param id {String} 
   * @param userId {String} 
   * @param messageType {String} 
   * @param createdAt {Date} 
   * @param conversationId {String} 
   */
  constructor(id, userId, messageType, createdAt, conversationId) {
    this.id = id;
    this.userId = userId;
    this.messageType = messageType;
    this.createdAt = createdAt;
    this.conversationId = conversationId;
  }

  /**
   * Constructs a <code>Memory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Memory} obj Optional instance to populate.
   * @return {module:model/Memory} The populated <code>Memory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Memory();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = PrismaModelsUser.constructFromObject(data['user']);
      if (data.hasOwnProperty('messageType'))
        obj.messageType = ApiClient.convertToType(data['messageType'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('conversationId'))
        obj.conversationId = ApiClient.convertToType(data['conversationId'], 'String');
      if (data.hasOwnProperty('conversation'))
        obj.conversation = Conversation.constructFromObject(data['conversation']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Memory.prototype.id = undefined;

/**
 * @member {String} userId
 */
Memory.prototype.userId = undefined;

/**
 * @member {module:model/PrismaModelsUser} user
 */
Memory.prototype.user = undefined;

/**
 * @member {String} messageType
 */
Memory.prototype.messageType = undefined;

/**
 * @member {String} message
 */
Memory.prototype.message = undefined;

/**
 * @member {Date} createdAt
 */
Memory.prototype.createdAt = undefined;

/**
 * @member {String} conversationId
 */
Memory.prototype.conversationId = undefined;

/**
 * @member {module:model/Conversation} conversation
 */
Memory.prototype.conversation = undefined;

