/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DatasourceStatus} from './DatasourceStatus';
import {DatasourceType} from './DatasourceType';
import {PrismaModelsSkillDatasource} from './PrismaModelsSkillDatasource';
import {PrismaModelsUser} from './PrismaModelsUser';

/**
 * The PrismaModelsDatasource model module.
 * @module model/PrismaModelsDatasource
 * @version 0.0.5
 */
export class PrismaModelsDatasource {
  /**
   * Constructs a new <code>PrismaModelsDatasource</code>.
   * Represents a Datasource record
   * @alias module:model/PrismaModelsDatasource
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param type {module:model/DatasourceType} 
   * @param userId {String} 
   * @param createdAt {Date} 
   * @param updatedAt {Date} 
   * @param status {module:model/DatasourceStatus} 
   */
  constructor(id, name, type, userId, createdAt, updatedAt, status) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.userId = userId;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.status = status;
  }

  /**
   * Constructs a <code>PrismaModelsDatasource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrismaModelsDatasource} obj Optional instance to populate.
   * @return {module:model/PrismaModelsDatasource} The populated <code>PrismaModelsDatasource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrismaModelsDatasource();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = DatasourceType.constructFromObject(data['type']);
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = PrismaModelsUser.constructFromObject(data['user']);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = DatasourceStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('datasources'))
        obj.datasources = ApiClient.convertToType(data['datasources'], [PrismaModelsSkillDatasource]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PrismaModelsDatasource.prototype.id = undefined;

/**
 * @member {String} name
 */
PrismaModelsDatasource.prototype.name = undefined;

/**
 * @member {String} content
 */
PrismaModelsDatasource.prototype.content = undefined;

/**
 * @member {String} description
 */
PrismaModelsDatasource.prototype.description = undefined;

/**
 * @member {String} url
 */
PrismaModelsDatasource.prototype.url = undefined;

/**
 * @member {module:model/DatasourceType} type
 */
PrismaModelsDatasource.prototype.type = undefined;

/**
 * @member {String} userId
 */
PrismaModelsDatasource.prototype.userId = undefined;

/**
 * @member {module:model/PrismaModelsUser} user
 */
PrismaModelsDatasource.prototype.user = undefined;

/**
 * @member {Date} createdAt
 */
PrismaModelsDatasource.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PrismaModelsDatasource.prototype.updatedAt = undefined;

/**
 * @member {String} metadata
 */
PrismaModelsDatasource.prototype.metadata = undefined;

/**
 * @member {module:model/DatasourceStatus} status
 */
PrismaModelsDatasource.prototype.status = undefined;

/**
 * @member {Array.<module:model/PrismaModelsSkillDatasource>} datasources
 */
PrismaModelsDatasource.prototype.datasources = undefined;

