/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PrismaModelsSkill} from './PrismaModelsSkill';
import {PrismaModelsTool} from './PrismaModelsTool';

/**
 * The PrismaModelsSkillTool model module.
 * @module model/PrismaModelsSkillTool
 * @version 0.0.5
 */
export class PrismaModelsSkillTool {
  /**
   * Constructs a new <code>PrismaModelsSkillTool</code>.
   * Represents a SkillTool record
   * @alias module:model/PrismaModelsSkillTool
   * @class
   * @param skillId {String} 
   * @param toolId {String} 
   * @param createdAt {Date} 
   * @param updatedAt {Date} 
   */
  constructor(skillId, toolId, createdAt, updatedAt) {
    this.skillId = skillId;
    this.toolId = toolId;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Constructs a <code>PrismaModelsSkillTool</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrismaModelsSkillTool} obj Optional instance to populate.
   * @return {module:model/PrismaModelsSkillTool} The populated <code>PrismaModelsSkillTool</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrismaModelsSkillTool();
      if (data.hasOwnProperty('skillId'))
        obj.skillId = ApiClient.convertToType(data['skillId'], 'String');
      if (data.hasOwnProperty('toolId'))
        obj.toolId = ApiClient.convertToType(data['toolId'], 'String');
      if (data.hasOwnProperty('skill'))
        obj.skill = PrismaModelsSkill.constructFromObject(data['skill']);
      if (data.hasOwnProperty('tool'))
        obj.tool = PrismaModelsTool.constructFromObject(data['tool']);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} skillId
 */
PrismaModelsSkillTool.prototype.skillId = undefined;

/**
 * @member {String} toolId
 */
PrismaModelsSkillTool.prototype.toolId = undefined;

/**
 * @member {module:model/PrismaModelsSkill} skill
 */
PrismaModelsSkillTool.prototype.skill = undefined;

/**
 * @member {module:model/PrismaModelsTool} tool
 */
PrismaModelsSkillTool.prototype.tool = undefined;

/**
 * @member {Date} createdAt
 */
PrismaModelsSkillTool.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PrismaModelsSkillTool.prototype.updatedAt = undefined;

