/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PrismaModelsAiden} from './PrismaModelsAiden';
import {PrismaModelsSkill} from './PrismaModelsSkill';

/**
 * The PrismaModelsAidenStep model module.
 * @module model/PrismaModelsAidenStep
 * @version 0.0.5
 */
export class PrismaModelsAidenStep {
  /**
   * Constructs a new <code>PrismaModelsAidenStep</code>.
   * Represents a AidenStep record
   * @alias module:model/PrismaModelsAidenStep
   * @class
   * @param id {String} 
   * @param order {Number} 
   * @param aidenId {String} 
   * @param createdAt {Date} 
   * @param updatedAt {Date} 
   * @param input {String} 
   * @param output {String} 
   * @param skillId {String} 
   */
  constructor(id, order, aidenId, createdAt, updatedAt, input, output, skillId) {
    this.id = id;
    this.order = order;
    this.aidenId = aidenId;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.input = input;
    this.output = output;
    this.skillId = skillId;
  }

  /**
   * Constructs a <code>PrismaModelsAidenStep</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrismaModelsAidenStep} obj Optional instance to populate.
   * @return {module:model/PrismaModelsAidenStep} The populated <code>PrismaModelsAidenStep</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrismaModelsAidenStep();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], 'Number');
      if (data.hasOwnProperty('aidenId'))
        obj.aidenId = ApiClient.convertToType(data['aidenId'], 'String');
      if (data.hasOwnProperty('aiden'))
        obj.aiden = PrismaModelsAiden.constructFromObject(data['aiden']);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], 'String');
      if (data.hasOwnProperty('output'))
        obj.output = ApiClient.convertToType(data['output'], 'String');
      if (data.hasOwnProperty('skillId'))
        obj.skillId = ApiClient.convertToType(data['skillId'], 'String');
      if (data.hasOwnProperty('skill'))
        obj.skill = PrismaModelsSkill.constructFromObject(data['skill']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PrismaModelsAidenStep.prototype.id = undefined;

/**
 * @member {Number} order
 */
PrismaModelsAidenStep.prototype.order = undefined;

/**
 * @member {String} aidenId
 */
PrismaModelsAidenStep.prototype.aidenId = undefined;

/**
 * @member {module:model/PrismaModelsAiden} aiden
 */
PrismaModelsAidenStep.prototype.aiden = undefined;

/**
 * @member {Date} createdAt
 */
PrismaModelsAidenStep.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PrismaModelsAidenStep.prototype.updatedAt = undefined;

/**
 * @member {String} input
 */
PrismaModelsAidenStep.prototype.input = undefined;

/**
 * @member {String} output
 */
PrismaModelsAidenStep.prototype.output = undefined;

/**
 * @member {String} skillId
 */
PrismaModelsAidenStep.prototype.skillId = undefined;

/**
 * @member {module:model/PrismaModelsSkill} skill
 */
PrismaModelsAidenStep.prototype.skill = undefined;

