/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PrismaModelsAidenStep} from './PrismaModelsAidenStep';
import {PrismaModelsSkillDatasource} from './PrismaModelsSkillDatasource';
import {PrismaModelsSkillTool} from './PrismaModelsSkillTool';
import {PrismaModelsUser} from './PrismaModelsUser';

/**
 * The PrismaModelsSkill model module.
 * @module model/PrismaModelsSkill
 * @version 0.0.5
 */
export class PrismaModelsSkill {
  /**
   * Constructs a new <code>PrismaModelsSkill</code>.
   * Represents a Skill record
   * @alias module:model/PrismaModelsSkill
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param description {String} 
   * @param isActive {Boolean} 
   * @param createdAt {Date} 
   * @param updatedAt {Date} 
   * @param userId {String} 
   */
  constructor(id, name, description, isActive, createdAt, updatedAt, userId) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.isActive = isActive;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.userId = userId;
  }

  /**
   * Constructs a <code>PrismaModelsSkill</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrismaModelsSkill} obj Optional instance to populate.
   * @return {module:model/PrismaModelsSkill} The populated <code>PrismaModelsSkill</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrismaModelsSkill();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('avatar'))
        obj.avatar = ApiClient.convertToType(data['avatar'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('prompt'))
        obj.prompt = ApiClient.convertToType(data['prompt'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = PrismaModelsUser.constructFromObject(data['user']);
      if (data.hasOwnProperty('datasources'))
        obj.datasources = ApiClient.convertToType(data['datasources'], [PrismaModelsSkillDatasource]);
      if (data.hasOwnProperty('tools'))
        obj.tools = ApiClient.convertToType(data['tools'], [PrismaModelsSkillTool]);
      if (data.hasOwnProperty('aidenSteps'))
        obj.aidenSteps = ApiClient.convertToType(data['aidenSteps'], [PrismaModelsAidenStep]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PrismaModelsSkill.prototype.id = undefined;

/**
 * @member {String} name
 */
PrismaModelsSkill.prototype.name = undefined;

/**
 * @member {String} avatar
 */
PrismaModelsSkill.prototype.avatar = undefined;

/**
 * @member {String} description
 */
PrismaModelsSkill.prototype.description = undefined;

/**
 * @member {Boolean} isActive
 */
PrismaModelsSkill.prototype.isActive = undefined;

/**
 * @member {Date} createdAt
 */
PrismaModelsSkill.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PrismaModelsSkill.prototype.updatedAt = undefined;

/**
 * @member {String} prompt
 */
PrismaModelsSkill.prototype.prompt = undefined;

/**
 * @member {String} userId
 */
PrismaModelsSkill.prototype.userId = undefined;

/**
 * @member {module:model/PrismaModelsUser} user
 */
PrismaModelsSkill.prototype.user = undefined;

/**
 * @member {Array.<module:model/PrismaModelsSkillDatasource>} datasources
 */
PrismaModelsSkill.prototype.datasources = undefined;

/**
 * @member {Array.<module:model/PrismaModelsSkillTool>} tools
 */
PrismaModelsSkill.prototype.tools = undefined;

/**
 * @member {Array.<module:model/PrismaModelsAidenStep>} aidenSteps
 */
PrismaModelsSkill.prototype.aidenSteps = undefined;

