/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PrismaModelsSkillTool} from './PrismaModelsSkillTool';
import {PrismaModelsUser} from './PrismaModelsUser';
import {ToolType} from './ToolType';

/**
 * The PrismaModelsTool model module.
 * @module model/PrismaModelsTool
 * @version 0.0.5
 */
export class PrismaModelsTool {
  /**
   * Constructs a new <code>PrismaModelsTool</code>.
   * Represents a Tool record
   * @alias module:model/PrismaModelsTool
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param description {String} 
   * @param type {module:model/ToolType} 
   * @param returnDirect {Boolean} 
   * @param metadata {String} 
   * @param createdAt {Date} 
   * @param updatedAt {Date} 
   * @param userId {String} 
   */
  constructor(id, name, description, type, returnDirect, metadata, createdAt, updatedAt, userId) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.type = type;
    this.returnDirect = returnDirect;
    this.metadata = metadata;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.userId = userId;
  }

  /**
   * Constructs a <code>PrismaModelsTool</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrismaModelsTool} obj Optional instance to populate.
   * @return {module:model/PrismaModelsTool} The populated <code>PrismaModelsTool</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrismaModelsTool();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ToolType.constructFromObject(data['type']);
      if (data.hasOwnProperty('returnDirect'))
        obj.returnDirect = ApiClient.convertToType(data['returnDirect'], 'Boolean');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = PrismaModelsUser.constructFromObject(data['user']);
      if (data.hasOwnProperty('tools'))
        obj.tools = ApiClient.convertToType(data['tools'], [PrismaModelsSkillTool]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PrismaModelsTool.prototype.id = undefined;

/**
 * @member {String} name
 */
PrismaModelsTool.prototype.name = undefined;

/**
 * @member {String} description
 */
PrismaModelsTool.prototype.description = undefined;

/**
 * @member {module:model/ToolType} type
 */
PrismaModelsTool.prototype.type = undefined;

/**
 * @member {Boolean} returnDirect
 */
PrismaModelsTool.prototype.returnDirect = undefined;

/**
 * @member {String} metadata
 */
PrismaModelsTool.prototype.metadata = undefined;

/**
 * @member {Date} createdAt
 */
PrismaModelsTool.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PrismaModelsTool.prototype.updatedAt = undefined;

/**
 * @member {String} userId
 */
PrismaModelsTool.prototype.userId = undefined;

/**
 * @member {module:model/PrismaModelsUser} user
 */
PrismaModelsTool.prototype.user = undefined;

/**
 * @member {Array.<module:model/PrismaModelsSkillTool>} tools
 */
PrismaModelsTool.prototype.tools = undefined;

