/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Conversation} from './Conversation';
import {Language} from './Language';
import {Memory} from './Memory';
import {PrismaModelsAiden} from './PrismaModelsAiden';
import {PrismaModelsDatasource} from './PrismaModelsDatasource';
import {PrismaModelsSkill} from './PrismaModelsSkill';
import {PrismaModelsTool} from './PrismaModelsTool';
import {UserType} from './UserType';

/**
 * The PrismaModelsUser model module.
 * @module model/PrismaModelsUser
 * @version 0.0.5
 */
export class PrismaModelsUser {
  /**
   * Constructs a new <code>PrismaModelsUser</code>.
   * Represents a User record
   * @alias module:model/PrismaModelsUser
   * @class
   * @param id {String} 
   * @param email {String} 
   * @param createdAt {Date} 
   */
  constructor(id, email, createdAt) {
    this.id = id;
    this.email = email;
    this.createdAt = createdAt;
  }

  /**
   * Constructs a <code>PrismaModelsUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrismaModelsUser} obj Optional instance to populate.
   * @return {module:model/PrismaModelsUser} The populated <code>PrismaModelsUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrismaModelsUser();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('avatar'))
        obj.avatar = ApiClient.convertToType(data['avatar'], 'String');
      if (data.hasOwnProperty('age'))
        obj.age = ApiClient.convertToType(data['age'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = UserType.constructFromObject(data['type']);
      if (data.hasOwnProperty('language'))
        obj.language = Language.constructFromObject(data['language']);
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('skills'))
        obj.skills = ApiClient.convertToType(data['skills'], [PrismaModelsSkill]);
      if (data.hasOwnProperty('datasources'))
        obj.datasources = ApiClient.convertToType(data['datasources'], [PrismaModelsDatasource]);
      if (data.hasOwnProperty('tools'))
        obj.tools = ApiClient.convertToType(data['tools'], [PrismaModelsTool]);
      if (data.hasOwnProperty('aiden'))
        obj.aiden = ApiClient.convertToType(data['aiden'], [PrismaModelsAiden]);
      if (data.hasOwnProperty('memories'))
        obj.memories = ApiClient.convertToType(data['memories'], [Memory]);
      if (data.hasOwnProperty('conversations'))
        obj.conversations = ApiClient.convertToType(data['conversations'], [Conversation]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PrismaModelsUser.prototype.id = undefined;

/**
 * @member {String} email
 */
PrismaModelsUser.prototype.email = undefined;

/**
 * @member {String} name
 */
PrismaModelsUser.prototype.name = undefined;

/**
 * @member {String} avatar
 */
PrismaModelsUser.prototype.avatar = undefined;

/**
 * @member {String} age
 */
PrismaModelsUser.prototype.age = undefined;

/**
 * @member {module:model/UserType} type
 */
PrismaModelsUser.prototype.type = undefined;

/**
 * @member {module:model/Language} language
 */
PrismaModelsUser.prototype.language = undefined;

/**
 * @member {String} metadata
 */
PrismaModelsUser.prototype.metadata = undefined;

/**
 * @member {Date} createdAt
 */
PrismaModelsUser.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
PrismaModelsUser.prototype.updatedAt = undefined;

/**
 * @member {Array.<module:model/PrismaModelsSkill>} skills
 */
PrismaModelsUser.prototype.skills = undefined;

/**
 * @member {Array.<module:model/PrismaModelsDatasource>} datasources
 */
PrismaModelsUser.prototype.datasources = undefined;

/**
 * @member {Array.<module:model/PrismaModelsTool>} tools
 */
PrismaModelsUser.prototype.tools = undefined;

/**
 * @member {Array.<module:model/PrismaModelsAiden>} aiden
 */
PrismaModelsUser.prototype.aiden = undefined;

/**
 * @member {Array.<module:model/Memory>} memories
 */
PrismaModelsUser.prototype.memories = undefined;

/**
 * @member {Array.<module:model/Conversation>} conversations
 */
PrismaModelsUser.prototype.conversations = undefined;

