/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class UserType.
 * @enum {String}
 * @readonly
 */
const UserType = {
  /**
   * value: "LEARNER"
   * @const
   */
  LEARNER: "LEARNER",

  /**
   * value: "EDUCATOR"
   * @const
   */
  EDUCATOR: "EDUCATOR",

  /**
   * value: "PROFESSIONAL"
   * @const
   */
  PROFESSIONAL: "PROFESSIONAL",

  /**
   * Returns a <code>UserType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/UserType} The enum <code>UserType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {UserType};