/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {AidenInvoke} from '../model/AidenInvoke';
import {AidenList} from '../model/AidenList';
import {AppModelsRequestAiden} from '../model/AppModelsRequestAiden';
import {AppModelsRequestAidenStep} from '../model/AppModelsRequestAidenStep';
import {AppModelsResponseAiden} from '../model/AppModelsResponseAiden';
import {HTTPValidationError} from '../model/HTTPValidationError';

/**
* Aiden service.
* @module api/AidenApi
* @version 0.0.5
*/
export class AidenApi {

    /**
    * Constructs a new AidenApi. 
    * @alias module:api/AidenApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addAidenStep operation.
     * @callback moduleapi/AidenApi~addAidenStepCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AppModelsResponseAiden{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Step
     * Create a new aiden step
     * @param {module:model/AppModelsRequestAidenStep} body 
     * @param {String} aidenId 
     * @param {module:api/AidenApi~addAidenStepCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    addAidenStep(body, aidenId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addAidenStep");
      }
      // verify the required parameter 'aidenId' is set
      if (aidenId === undefined || aidenId === null) {
        throw new Error("Missing the required parameter 'aidenId' when calling addAidenStep");
      }

      let pathParams = {
        'aiden_id': aidenId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AppModelsResponseAiden;

      return this.apiClient.callApi(
        '/api/v1/aiden/{aiden_id}/steps', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the createAiden operation.
     * @callback moduleapi/AidenApi~createAidenCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AppModelsResponseAiden{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create
     * Create a new aiden
     * @param {module:model/AppModelsRequestAiden} body 
     * @param {module:api/AidenApi~createAidenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createAiden(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createAiden");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AppModelsResponseAiden;

      return this.apiClient.callApi(
        '/api/v1/aiden', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deleteAiden operation.
     * @callback moduleapi/AidenApi~deleteAidenCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete
     * Delete a specific aiden
     * @param {String} aidenId 
     * @param {module:api/AidenApi~deleteAidenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    deleteAiden(aidenId, callback) {
      
      let postBody = null;
      // verify the required parameter 'aidenId' is set
      if (aidenId === undefined || aidenId === null) {
        throw new Error("Missing the required parameter 'aidenId' when calling deleteAiden");
      }

      let pathParams = {
        'aiden_id': aidenId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/api/v1/aiden/{aiden_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deleteAidenStep operation.
     * @callback moduleapi/AidenApi~deleteAidenStepCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Step
     * Delete a specific aiden step
     * @param {String} aidenId 
     * @param {String} stepId 
     * @param {module:api/AidenApi~deleteAidenStepCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    deleteAidenStep(aidenId, stepId, callback) {
      
      let postBody = null;
      // verify the required parameter 'aidenId' is set
      if (aidenId === undefined || aidenId === null) {
        throw new Error("Missing the required parameter 'aidenId' when calling deleteAidenStep");
      }
      // verify the required parameter 'stepId' is set
      if (stepId === undefined || stepId === null) {
        throw new Error("Missing the required parameter 'stepId' when calling deleteAidenStep");
      }

      let pathParams = {
        'aiden_id': aidenId,'step_id': stepId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/api/v1/aiden/{aiden_id}/steps/{step_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getAiden operation.
     * @callback moduleapi/AidenApi~getAidenCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AppModelsResponseAiden{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get
     * Get a single aiden
     * @param {String} aidenId 
     * @param {module:api/AidenApi~getAidenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getAiden(aidenId, callback) {
      
      let postBody = null;
      // verify the required parameter 'aidenId' is set
      if (aidenId === undefined || aidenId === null) {
        throw new Error("Missing the required parameter 'aidenId' when calling getAiden");
      }

      let pathParams = {
        'aiden_id': aidenId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AppModelsResponseAiden;

      return this.apiClient.callApi(
        '/api/v1/aiden/{aiden_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the invokeAiden operation.
     * @callback moduleapi/AidenApi~invokeAidenCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Invoke
     * Invoke a specific aiden
     * @param {module:model/AidenInvoke} body 
     * @param {String} aidenId 
     * @param {module:api/AidenApi~invokeAidenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    invokeAiden(body, aidenId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling invokeAiden");
      }
      // verify the required parameter 'aidenId' is set
      if (aidenId === undefined || aidenId === null) {
        throw new Error("Missing the required parameter 'aidenId' when calling invokeAiden");
      }

      let pathParams = {
        'aiden_id': aidenId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/api/v1/aiden/{aiden_id}/invoke', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listAidenSteps operation.
     * @callback moduleapi/AidenApi~listAidenStepsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AidenList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List Steps
     * List all steps of a aiden
     * @param {String} aidenId 
     * @param {module:api/AidenApi~listAidenStepsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listAidenSteps(aidenId, callback) {
      
      let postBody = null;
      // verify the required parameter 'aidenId' is set
      if (aidenId === undefined || aidenId === null) {
        throw new Error("Missing the required parameter 'aidenId' when calling listAidenSteps");
      }

      let pathParams = {
        'aiden_id': aidenId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AidenList;

      return this.apiClient.callApi(
        '/api/v1/aiden/{aiden_id}/steps', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listAidens operation.
     * @callback moduleapi/AidenApi~listAidensCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AidenList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List
     * List all aiden
     * @param {module:api/AidenApi~listAidensCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listAidens(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AidenList;

      return this.apiClient.callApi(
        '/api/v1/aiden', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateAiden operation.
     * @callback moduleapi/AidenApi~updateAidenCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AppModelsResponseAiden{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update
     * Patch a aiden
     * @param {module:model/AppModelsRequestAiden} body 
     * @param {String} aidenId 
     * @param {module:api/AidenApi~updateAidenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    updateAiden(body, aidenId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateAiden");
      }
      // verify the required parameter 'aidenId' is set
      if (aidenId === undefined || aidenId === null) {
        throw new Error("Missing the required parameter 'aidenId' when calling updateAiden");
      }

      let pathParams = {
        'aiden_id': aidenId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AppModelsResponseAiden;

      return this.apiClient.callApi(
        '/api/v1/aiden/{aiden_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}