/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {AppModelsRequestDatasource} from '../model/AppModelsRequestDatasource';
import {AppModelsResponseDatasource} from '../model/AppModelsResponseDatasource';
import {DatasourceList} from '../model/DatasourceList';
import {HTTPValidationError} from '../model/HTTPValidationError';

/**
* Datasource service.
* @module api/DatasourceApi
* @version 0.0.5
*/
export class DatasourceApi {

    /**
    * Constructs a new DatasourceApi. 
    * @alias module:api/DatasourceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createApiV1DatasourcesPost operation.
     * @callback moduleapi/DatasourceApi~createApiV1DatasourcesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AppModelsResponseDatasource{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create
     * Create a new datasource
     * @param {module:model/AppModelsRequestDatasource} body 
     * @param {module:api/DatasourceApi~createApiV1DatasourcesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createApiV1DatasourcesPost(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createApiV1DatasourcesPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AppModelsResponseDatasource;

      return this.apiClient.callApi(
        '/api/v1/datasources', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deleteApiV1DatasourcesDatasourceIdDelete operation.
     * @callback moduleapi/DatasourceApi~deleteApiV1DatasourcesDatasourceIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete
     * Delete a specific datasource
     * @param {String} datasourceId 
     * @param {module:api/DatasourceApi~deleteApiV1DatasourcesDatasourceIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    deleteApiV1DatasourcesDatasourceIdDelete(datasourceId, callback) {
      
      let postBody = null;
      // verify the required parameter 'datasourceId' is set
      if (datasourceId === undefined || datasourceId === null) {
        throw new Error("Missing the required parameter 'datasourceId' when calling deleteApiV1DatasourcesDatasourceIdDelete");
      }

      let pathParams = {
        'datasource_id': datasourceId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/api/v1/datasources/{datasource_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getApiV1DatasourcesDatasourceIdGet operation.
     * @callback moduleapi/DatasourceApi~getApiV1DatasourcesDatasourceIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AppModelsResponseDatasource{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get
     * Get a specific datasource
     * @param {String} datasourceId 
     * @param {module:api/DatasourceApi~getApiV1DatasourcesDatasourceIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getApiV1DatasourcesDatasourceIdGet(datasourceId, callback) {
      
      let postBody = null;
      // verify the required parameter 'datasourceId' is set
      if (datasourceId === undefined || datasourceId === null) {
        throw new Error("Missing the required parameter 'datasourceId' when calling getApiV1DatasourcesDatasourceIdGet");
      }

      let pathParams = {
        'datasource_id': datasourceId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AppModelsResponseDatasource;

      return this.apiClient.callApi(
        '/api/v1/datasources/{datasource_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listApiV1DatasourcesGet operation.
     * @callback moduleapi/DatasourceApi~listApiV1DatasourcesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DatasourceList{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List
     * List all datasources
     * @param {module:api/DatasourceApi~listApiV1DatasourcesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listApiV1DatasourcesGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DatasourceList;

      return this.apiClient.callApi(
        '/api/v1/datasources', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateApiV1DatasourcesDatasourceIdPatch operation.
     * @callback moduleapi/DatasourceApi~updateApiV1DatasourcesDatasourceIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AppModelsResponseDatasource{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update
     * Update a specific datasource
     * @param {module:model/AppModelsRequestDatasource} body 
     * @param {String} datasourceId 
     * @param {module:api/DatasourceApi~updateApiV1DatasourcesDatasourceIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    updateApiV1DatasourcesDatasourceIdPatch(body, datasourceId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateApiV1DatasourcesDatasourceIdPatch");
      }
      // verify the required parameter 'datasourceId' is set
      if (datasourceId === undefined || datasourceId === null) {
        throw new Error("Missing the required parameter 'datasourceId' when calling updateApiV1DatasourcesDatasourceIdPatch");
      }

      let pathParams = {
        'datasource_id': datasourceId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AppModelsResponseDatasource;

      return this.apiClient.callApi(
        '/api/v1/datasources/{datasource_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}