/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Askaiden);
  }
}(this, function(expect, Askaiden) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Language', function() {
      beforeEach(function() {
        instance = Askaiden.Language;
      });

      it('should create an instance of Language', function() {
        // TODO: update the code to test Language
        expect(instance).to.be.a('object');
      });

      it('should have the property GERMAN', function() {
        expect(instance).to.have.property('GERMAN');
        expect(instance.GERMAN).to.be("GERMAN");
      });

      it('should have the property FRANCE', function() {
        expect(instance).to.have.property('FRANCE');
        expect(instance.FRANCE).to.be("FRANCE");
      });

      it('should have the property ENGLISH', function() {
        expect(instance).to.have.property('ENGLISH');
        expect(instance.ENGLISH).to.be("ENGLISH");
      });

      it('should have the property SPAIN', function() {
        expect(instance).to.have.property('SPAIN');
        expect(instance.SPAIN).to.be("SPAIN");
      });

    });
  });

}));
