/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Askaiden);
  }
}(this, function(expect, Askaiden) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PrismaModelsSkillTool', function() {
      beforeEach(function() {
        instance = new Askaiden.PrismaModelsSkillTool();
      });

      it('should create an instance of PrismaModelsSkillTool', function() {
        // TODO: update the code to test PrismaModelsSkillTool
        expect(instance).to.be.a(Askaiden.PrismaModelsSkillTool);
      });

      it('should have the property skillId (base name: "skillId")', function() {
        // TODO: update the code to test the property skillId
        expect(instance).to.have.property('skillId');
        // expect(instance.skillId).to.be(expectedValueLiteral);
      });

      it('should have the property toolId (base name: "toolId")', function() {
        // TODO: update the code to test the property toolId
        expect(instance).to.have.property('toolId');
        // expect(instance.toolId).to.be(expectedValueLiteral);
      });

      it('should have the property skill (base name: "skill")', function() {
        // TODO: update the code to test the property skill
        expect(instance).to.have.property('skill');
        // expect(instance.skill).to.be(expectedValueLiteral);
      });

      it('should have the property tool (base name: "tool")', function() {
        // TODO: update the code to test the property tool
        expect(instance).to.have.property('tool');
        // expect(instance.tool).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updatedAt")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
