/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AidenInvoke} from './model/AidenInvoke';
import {AidenList} from './model/AidenList';
import {AnyOfValidationErrorLocItems} from './model/AnyOfValidationErrorLocItems';
import {AppModelsRequestAiden} from './model/AppModelsRequestAiden';
import {AppModelsRequestAidenStep} from './model/AppModelsRequestAidenStep';
import {AppModelsRequestDatasource} from './model/AppModelsRequestDatasource';
import {AppModelsRequestSkill} from './model/AppModelsRequestSkill';
import {AppModelsRequestSkillDatasource} from './model/AppModelsRequestSkillDatasource';
import {AppModelsRequestSkillInvoke} from './model/AppModelsRequestSkillInvoke';
import {AppModelsRequestSkillTool} from './model/AppModelsRequestSkillTool';
import {AppModelsRequestTool} from './model/AppModelsRequestTool';
import {AppModelsRequestUser} from './model/AppModelsRequestUser';
import {AppModelsResponseAiden} from './model/AppModelsResponseAiden';
import {AppModelsResponseDatasource} from './model/AppModelsResponseDatasource';
import {AppModelsResponseSkill} from './model/AppModelsResponseSkill';
import {AppModelsResponseSkillInvoke} from './model/AppModelsResponseSkillInvoke';
import {AppModelsResponseTool} from './model/AppModelsResponseTool';
import {AppModelsResponseUser} from './model/AppModelsResponseUser';
import {Conversation} from './model/Conversation';
import {ConversationCreation} from './model/ConversationCreation';
import {ConversationDefinition} from './model/ConversationDefinition';
import {DatasourceList} from './model/DatasourceList';
import {DatasourceStatus} from './model/DatasourceStatus';
import {DatasourceType} from './model/DatasourceType';
import {HTTPValidationError} from './model/HTTPValidationError';
import {Language} from './model/Language';
import {Memory} from './model/Memory';
import {PrismaModelsAiden} from './model/PrismaModelsAiden';
import {PrismaModelsAidenStep} from './model/PrismaModelsAidenStep';
import {PrismaModelsDatasource} from './model/PrismaModelsDatasource';
import {PrismaModelsSkill} from './model/PrismaModelsSkill';
import {PrismaModelsSkillDatasource} from './model/PrismaModelsSkillDatasource';
import {PrismaModelsSkillTool} from './model/PrismaModelsSkillTool';
import {PrismaModelsTool} from './model/PrismaModelsTool';
import {PrismaModelsUser} from './model/PrismaModelsUser';
import {SkillDatasosurceList} from './model/SkillDatasosurceList';
import {SkillList} from './model/SkillList';
import {SkillRunList} from './model/SkillRunList';
import {SkillToolList} from './model/SkillToolList';
import {ToolList} from './model/ToolList';
import {ToolType} from './model/ToolType';
import {UserType} from './model/UserType';
import {ValidationError} from './model/ValidationError';
import {AidenApi} from './api/AidenApi';
import {ConversationsApi} from './api/ConversationsApi';
import {DatasourceApi} from './api/DatasourceApi';
import {SkillsApi} from './api/SkillsApi';
import {ToolApi} from './api/ToolApi';
import {UsersApi} from './api/UsersApi';

/**
* The_operating_system_to_build_AI_Tutors.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Askaiden = require('index'); // See note below*.
* var xxxSvc = new Askaiden.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Askaiden.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Askaiden.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Askaiden.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.5
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AidenInvoke model constructor.
     * @property {module:model/AidenInvoke}
     */
    AidenInvoke,

    /**
     * The AidenList model constructor.
     * @property {module:model/AidenList}
     */
    AidenList,

    /**
     * The AnyOfValidationErrorLocItems model constructor.
     * @property {module:model/AnyOfValidationErrorLocItems}
     */
    AnyOfValidationErrorLocItems,

    /**
     * The AppModelsRequestAiden model constructor.
     * @property {module:model/AppModelsRequestAiden}
     */
    AppModelsRequestAiden,

    /**
     * The AppModelsRequestAidenStep model constructor.
     * @property {module:model/AppModelsRequestAidenStep}
     */
    AppModelsRequestAidenStep,

    /**
     * The AppModelsRequestDatasource model constructor.
     * @property {module:model/AppModelsRequestDatasource}
     */
    AppModelsRequestDatasource,

    /**
     * The AppModelsRequestSkill model constructor.
     * @property {module:model/AppModelsRequestSkill}
     */
    AppModelsRequestSkill,

    /**
     * The AppModelsRequestSkillDatasource model constructor.
     * @property {module:model/AppModelsRequestSkillDatasource}
     */
    AppModelsRequestSkillDatasource,

    /**
     * The AppModelsRequestSkillInvoke model constructor.
     * @property {module:model/AppModelsRequestSkillInvoke}
     */
    AppModelsRequestSkillInvoke,

    /**
     * The AppModelsRequestSkillTool model constructor.
     * @property {module:model/AppModelsRequestSkillTool}
     */
    AppModelsRequestSkillTool,

    /**
     * The AppModelsRequestTool model constructor.
     * @property {module:model/AppModelsRequestTool}
     */
    AppModelsRequestTool,

    /**
     * The AppModelsRequestUser model constructor.
     * @property {module:model/AppModelsRequestUser}
     */
    AppModelsRequestUser,

    /**
     * The AppModelsResponseAiden model constructor.
     * @property {module:model/AppModelsResponseAiden}
     */
    AppModelsResponseAiden,

    /**
     * The AppModelsResponseDatasource model constructor.
     * @property {module:model/AppModelsResponseDatasource}
     */
    AppModelsResponseDatasource,

    /**
     * The AppModelsResponseSkill model constructor.
     * @property {module:model/AppModelsResponseSkill}
     */
    AppModelsResponseSkill,

    /**
     * The AppModelsResponseSkillInvoke model constructor.
     * @property {module:model/AppModelsResponseSkillInvoke}
     */
    AppModelsResponseSkillInvoke,

    /**
     * The AppModelsResponseTool model constructor.
     * @property {module:model/AppModelsResponseTool}
     */
    AppModelsResponseTool,

    /**
     * The AppModelsResponseUser model constructor.
     * @property {module:model/AppModelsResponseUser}
     */
    AppModelsResponseUser,

    /**
     * The Conversation model constructor.
     * @property {module:model/Conversation}
     */
    Conversation,

    /**
     * The ConversationCreation model constructor.
     * @property {module:model/ConversationCreation}
     */
    ConversationCreation,

    /**
     * The ConversationDefinition model constructor.
     * @property {module:model/ConversationDefinition}
     */
    ConversationDefinition,

    /**
     * The DatasourceList model constructor.
     * @property {module:model/DatasourceList}
     */
    DatasourceList,

    /**
     * The DatasourceStatus model constructor.
     * @property {module:model/DatasourceStatus}
     */
    DatasourceStatus,

    /**
     * The DatasourceType model constructor.
     * @property {module:model/DatasourceType}
     */
    DatasourceType,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The Language model constructor.
     * @property {module:model/Language}
     */
    Language,

    /**
     * The Memory model constructor.
     * @property {module:model/Memory}
     */
    Memory,

    /**
     * The PrismaModelsAiden model constructor.
     * @property {module:model/PrismaModelsAiden}
     */
    PrismaModelsAiden,

    /**
     * The PrismaModelsAidenStep model constructor.
     * @property {module:model/PrismaModelsAidenStep}
     */
    PrismaModelsAidenStep,

    /**
     * The PrismaModelsDatasource model constructor.
     * @property {module:model/PrismaModelsDatasource}
     */
    PrismaModelsDatasource,

    /**
     * The PrismaModelsSkill model constructor.
     * @property {module:model/PrismaModelsSkill}
     */
    PrismaModelsSkill,

    /**
     * The PrismaModelsSkillDatasource model constructor.
     * @property {module:model/PrismaModelsSkillDatasource}
     */
    PrismaModelsSkillDatasource,

    /**
     * The PrismaModelsSkillTool model constructor.
     * @property {module:model/PrismaModelsSkillTool}
     */
    PrismaModelsSkillTool,

    /**
     * The PrismaModelsTool model constructor.
     * @property {module:model/PrismaModelsTool}
     */
    PrismaModelsTool,

    /**
     * The PrismaModelsUser model constructor.
     * @property {module:model/PrismaModelsUser}
     */
    PrismaModelsUser,

    /**
     * The SkillDatasosurceList model constructor.
     * @property {module:model/SkillDatasosurceList}
     */
    SkillDatasosurceList,

    /**
     * The SkillList model constructor.
     * @property {module:model/SkillList}
     */
    SkillList,

    /**
     * The SkillRunList model constructor.
     * @property {module:model/SkillRunList}
     */
    SkillRunList,

    /**
     * The SkillToolList model constructor.
     * @property {module:model/SkillToolList}
     */
    SkillToolList,

    /**
     * The ToolList model constructor.
     * @property {module:model/ToolList}
     */
    ToolList,

    /**
     * The ToolType model constructor.
     * @property {module:model/ToolType}
     */
    ToolType,

    /**
     * The UserType model constructor.
     * @property {module:model/UserType}
     */
    UserType,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The AidenApi service constructor.
    * @property {module:api/AidenApi}
    */
    AidenApi,

    /**
    * The ConversationsApi service constructor.
    * @property {module:api/ConversationsApi}
    */
    ConversationsApi,

    /**
    * The DatasourceApi service constructor.
    * @property {module:api/DatasourceApi}
    */
    DatasourceApi,

    /**
    * The SkillsApi service constructor.
    * @property {module:api/SkillsApi}
    */
    SkillsApi,

    /**
    * The ToolApi service constructor.
    * @property {module:api/ToolApi}
    */
    ToolApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
