/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Askaiden);
  }
}(this, function(expect, Askaiden) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Askaiden.AidenApi();
  });

  describe('(package)', function() {
    describe('AidenApi', function() {
      describe('addAidenStep', function() {
        it('should call addAidenStep successfully', function(done) {
          // TODO: uncomment, update parameter values for addAidenStep call and complete the assertions
          /*

          instance.addAidenStep(body, aidenId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseAiden);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createAiden', function() {
        it('should call createAiden successfully', function(done) {
          // TODO: uncomment, update parameter values for createAiden call and complete the assertions
          /*

          instance.createAiden(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseAiden);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteAiden', function() {
        it('should call deleteAiden successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteAiden call and complete the assertions
          /*

          instance.deleteAiden(aidenId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteAidenStep', function() {
        it('should call deleteAidenStep successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteAidenStep call and complete the assertions
          /*

          instance.deleteAidenStep(aidenId, stepId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAiden', function() {
        it('should call getAiden successfully', function(done) {
          // TODO: uncomment, update parameter values for getAiden call and complete the assertions
          /*

          instance.getAiden(aidenId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseAiden);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('invokeAiden', function() {
        it('should call invokeAiden successfully', function(done) {
          // TODO: uncomment, update parameter values for invokeAiden call and complete the assertions
          /*

          instance.invokeAiden(body, aidenId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listAidenSteps', function() {
        it('should call listAidenSteps successfully', function(done) {
          // TODO: uncomment, update parameter values for listAidenSteps call and complete the assertions
          /*

          instance.listAidenSteps(aidenId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AidenList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listAidens', function() {
        it('should call listAidens successfully', function(done) {
          // TODO: uncomment listAidens call and complete the assertions
          /*

          instance.listAidens(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AidenList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateAiden', function() {
        it('should call updateAiden successfully', function(done) {
          // TODO: uncomment, update parameter values for updateAiden call and complete the assertions
          /*

          instance.updateAiden(body, aidenId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseAiden);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
