/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Askaiden);
  }
}(this, function(expect, Askaiden) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Askaiden.DatasourceApi();
  });

  describe('(package)', function() {
    describe('DatasourceApi', function() {
      describe('createApiV1DatasourcesPost', function() {
        it('should call createApiV1DatasourcesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for createApiV1DatasourcesPost call and complete the assertions
          /*

          instance.createApiV1DatasourcesPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseDatasource);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteApiV1DatasourcesDatasourceIdDelete', function() {
        it('should call deleteApiV1DatasourcesDatasourceIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteApiV1DatasourcesDatasourceIdDelete call and complete the assertions
          /*

          instance.deleteApiV1DatasourcesDatasourceIdDelete(datasourceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getApiV1DatasourcesDatasourceIdGet', function() {
        it('should call getApiV1DatasourcesDatasourceIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for getApiV1DatasourcesDatasourceIdGet call and complete the assertions
          /*

          instance.getApiV1DatasourcesDatasourceIdGet(datasourceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseDatasource);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listApiV1DatasourcesGet', function() {
        it('should call listApiV1DatasourcesGet successfully', function(done) {
          // TODO: uncomment listApiV1DatasourcesGet call and complete the assertions
          /*

          instance.listApiV1DatasourcesGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.DatasourceList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateApiV1DatasourcesDatasourceIdPatch', function() {
        it('should call updateApiV1DatasourcesDatasourceIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for updateApiV1DatasourcesDatasourceIdPatch call and complete the assertions
          /*

          instance.updateApiV1DatasourcesDatasourceIdPatch(body, datasourceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseDatasource);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
