/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Askaiden);
  }
}(this, function(expect, Askaiden) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Askaiden.DatasourceApi();
  });

  describe('(package)', function() {
    describe('DatasourceApi', function() {
      describe('createDatasources', function() {
        it('should call createDatasources successfully', function(done) {
          // TODO: uncomment, update parameter values for createDatasources call and complete the assertions
          /*

          instance.createDatasources(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseDatasource);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteDatasource', function() {
        it('should call deleteDatasource successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteDatasource call and complete the assertions
          /*

          instance.deleteDatasource(datasourceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDatasource', function() {
        it('should call getDatasource successfully', function(done) {
          // TODO: uncomment, update parameter values for getDatasource call and complete the assertions
          /*

          instance.getDatasource(datasourceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseDatasource);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listDatasources', function() {
        it('should call listDatasources successfully', function(done) {
          // TODO: uncomment listDatasources call and complete the assertions
          /*

          instance.listDatasources(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.DatasourceList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateDatasource', function() {
        it('should call updateDatasource successfully', function(done) {
          // TODO: uncomment, update parameter values for updateDatasource call and complete the assertions
          /*

          instance.updateDatasource(body, datasourceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseDatasource);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
