/*
 * askaiden
 * The operating system to build AI Tutors
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Askaiden);
  }
}(this, function(expect, Askaiden) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Askaiden.ToolApi();
  });

  describe('(package)', function() {
    describe('ToolApi', function() {
      describe('createApiV1ToolsPost', function() {
        it('should call createApiV1ToolsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for createApiV1ToolsPost call and complete the assertions
          /*

          instance.createApiV1ToolsPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseTool);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteApiV1ToolsToolIdDelete', function() {
        it('should call deleteApiV1ToolsToolIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteApiV1ToolsToolIdDelete call and complete the assertions
          /*

          instance.deleteApiV1ToolsToolIdDelete(toolId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getApiV1ToolsToolIdGet', function() {
        it('should call getApiV1ToolsToolIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for getApiV1ToolsToolIdGet call and complete the assertions
          /*

          instance.getApiV1ToolsToolIdGet(toolId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseTool);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listApiV1ToolsGet', function() {
        it('should call listApiV1ToolsGet successfully', function(done) {
          // TODO: uncomment listApiV1ToolsGet call and complete the assertions
          /*

          instance.listApiV1ToolsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.ToolList);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateApiV1ToolsToolIdPatch', function() {
        it('should call updateApiV1ToolsToolIdPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for updateApiV1ToolsToolIdPatch call and complete the assertions
          /*

          instance.updateApiV1ToolsToolIdPatch(body, toolId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Askaiden.AppModelsResponseTool);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
